// <auto-generated />
namespace _14_RestaurantRater.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddedratingtoRestaurant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedratingtoRestaurant));
        
        string IMigrationMetadata.Id
        {
            get { return "202109011812434_Added rating to Restaurant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
